### ISSUE TITLE
关于api key

### ISSUE THREAD

**Issue by valloside** [Love-Kogasa/GensokyoMail#1]
现在gpt-4o和4o-mini不是随便用吗，为何还要花冤枉钱?

**Comment by Love-Kogasa** [comment]
gpt-4o 在 hk 那边也是要钱的
不过mini确实相当便宜，我也是最近才知道，我最开始是怕mini不知道幻想乡
然后这两天测试了一下发现可以，后面我会把模型换成更便宜的gpt-4o-mini

**Comment by valloside** [comment]
这俩都是有openai账号就能用的，而且4o-mini没有限额，注册又不用手机号，注册完就能拿access token然后转成api key，完全够用，不够再注册就行了

**Comment by Love-Kogasa** [comment]
我怕国人连不上，另外我这边也连的太慢
还是为了大家的体验考虑吧
Hk那边也挺便宜的，就先这样吧

**Comment by valloside** [comment]
转api是会走中转的，现在公益中转都有很多，我这也有现成的

**Comment by Love-Kogasa** [comment]
我知道啊，但是不稳定
比如 free.v36.cm
仅供个人和教学使用
主要还是不稳定

**Comment by valloside** [comment]
你这个key都不是自己的，本质就是卖key的商家，当然不稳啦，我说的是把普号的access token当成api key来用的那种，比如就有开源的https://github.com/lanqian528/chat2api

**Comment by Love-Kogasa** [comment]
嗯嗯，我看看有时间
